### PR TITLE
Using docker for dev environment

### PR DESCRIPTION
**Pull request by benburwell**
@jmankhan, here's a start to using Docker for managing the dev environment (and in particular postgres). It feels a little all over the place right now, so I'd like to get it a bit more ship-shape. Perhaps we can remove gulp from the toolchain?

Heroku also supports deploying docker containers, so that might be something to look into as well.

### CODE REVIEW

**Comment by benburwell** [comment]
@jmankhan, if you could try this out and make sure it works for you, that would be great. Once you verify this, go ahead and merge the PR. Thanks!

**Comment by jmankhan** [comment]
hmm, well i've run into the slight issue of my laptop being 32 bit, so i can't install docker.
i can try running this on my desktop, but i'll have to install linux on it

**Comment by jmankhan** [comment]
i'll do that asap and let you know if it gets up and running

**Comment by benburwell** [comment]
Any luck with this, @jmankhan?

**Pull request merged**
